docker:
  image: yegor256/rultor-image:1.20.0
assets:
  rubygems.yml: yegor256/home#assets/rubygems.yml
install: |
  pdd -f /dev/null
  sudo bundle install --no-color "--gemfile=$(pwd)/Gemfile"
  sudo apt-get -y install plantuml
release:
  script: |-
    bundle exec rake
    rm -rf *.gem
    sed -i "s/1\.0\.snapshot/${tag}/g" lib/version.rb
    git add lib/version.rb
    git commit -m "version set to ${tag}"
    gem build jekyll-plantuml.gemspec
    chmod 0600 ../rubygems.yml
    gem push *.gem --config-file ../rubygems.yml
merge:
  script: |-
    bundle exec rake
